openapi: 3.0.2
info:
  version: impl
  title: 'Wet Grass Bayes'
  description: hello wet grass
servers:
  - url: /jue/wetgrassbn/impl
    description: Wet Grass Bayesian Network
paths:
  /calculate:
    post:
      description: performs inteference calculation.
      operationId: calculate
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
      x-kgrid-activation:
        artifact: src/index.js
        adapter: JAVASCRIPT
        entry: calculate
components:
  schemas:
    input:
      required:
        - cloudy
        - sprinkler
        - rain
        - wetgrass
      properties:
        cloudy:
          type: string
          example: null
        sprinkler:
          type: string
          example: null
        rain:
          type: string
          example: null
        wetgrass:
          type: string
          example: null
    output:
      required:
        - result
      properties:
        result:
          type: object
